/**
 * Emits `supabase/seed.sql` from the validated catalog in `catalog.ts`.
 * Run: `npm run seed:build`. Importing catalog.ts alone runs all zod validation
 * and coherence checks (it throws on any problem), so a successful build IS a
 * validation pass. Do not hand-edit seed.sql — regenerate.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { catalog } from "./catalog";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "seed.sql");

// ── SQL literal helpers ──────────────────────────────────────────────────────
const s = (v: string): string => `'${v.replace(/'/g, "''")}'`;
const j = (v: unknown): string => `${s(JSON.stringify(v))}::jsonb`;
const n = (v: number): string => String(v);
const uuid = (v: string): string => s(v);
const nullable = (v: string | null): string => (v === null ? "NULL" : s(v));

const rows = (vals: string[][]): string => vals.map((r) => `  (${r.join(", ")})`).join(",\n");

const { company, materials, gltfAssets, styles, products, primarySpeciesId } = catalog;
const out: string[] = [];

out.push(`-- GENERATED by supabase/seed/build.ts — do not edit by hand. Run: npm run seed:build`);
out.push(`-- The curated v1 placeholder catalog (build-path step 2). Runs on \`supabase db reset\`.`);
out.push(`-- Every JSONB payload below was validated against lib/catalog/ at generation time (ADR 0014).`);
out.push("");

// company (default species set after materials exist — circular FK)
out.push(`insert into company (id, slug, name, rfq_recipient_email, quantize_increment_inch) values`);
out.push(
  `  (${uuid(company.id)}, ${s(company.slug)}, ${s(company.name)}, ${s(company.rfq_recipient_email)}, ${n(company.quantize_increment_inch)});`,
);
out.push("");

// materials
out.push(`insert into material (id, company_id, code, display_name, kind, render) values`);
out.push(
  rows(materials.map((m) => [uuid(m.id), uuid(m.company_id), s(m.code), s(m.display_name), s(m.kind), j(m.render)])) + ";",
);
out.push("");

// resolve the company's default Primary Species now that materials exist (ADR 0021)
out.push(`update company set default_primary_species_material_id = ${uuid(primarySpeciesId)} where id = ${uuid(company.id)};`);
out.push("");

// gltf assets
out.push(`insert into gltf_asset (id, company_id, storage_path, display_name) values`);
out.push(rows(gltfAssets.map((a) => [uuid(a.id), uuid(a.company_id), s(a.storage_path), nullable(a.display_name)])) + ";");
out.push("");

// styles
out.push(`insert into style (id, company_id, code, display_name, part_type, gltf_asset_id, anchor_scale_spec) values`);
out.push(
  rows(styles.map((st) => [uuid(st.id), uuid(st.company_id), s(st.code), s(st.display_name), s(st.part_type), uuid(st.gltf_asset_id), j(st.anchor_scale_spec)])) + ";",
);
out.push("");

// products (default_sku_id set after skus exist — circular FK)
out.push(
  `insert into product (id, company_id, code, display_name, part_type, selection_axes, dimension_bindings, match_keys, rail_system, splice_policy, default_axis_values) values`,
);
out.push(
  rows(products.map((p) => [
    uuid(p.id), uuid(p.company_id), s(p.code), s(p.display_name), s(p.part_type),
    j(p.selection_axes), j(p.dimension_bindings), j(p.match_keys), s(p.rail_system),
    p.splice_policy === null ? "NULL" : s(p.splice_policy), j(p.default_axis_values),
  ])) + ";",
);
out.push("");

// skus
const skuRows = products.flatMap((p) =>
  p.skus.map((sk) => [
    uuid(sk.id), uuid(sk.company_id), uuid(sk.product_id), s(sk.code),
    nullable(sk.style_id), nullable(sk.profile), uuid(sk.material_id),
    s(sk.rail_system), j(sk.axis_values), j(sk.stock_dimensions),
  ]),
);
out.push(`insert into sku (id, company_id, product_id, code, style_id, profile, material_id, rail_system, axis_values, stock_dimensions) values`);
out.push(rows(skuRows) + ";");
out.push("");

// resolve each product's curated default SKU (ADR 0021)
out.push(`-- curated default SKU per product (ADR 0021)`);
for (const p of products) {
  out.push(`update product set default_sku_id = ${uuid(p.default_sku_id)} where id = ${uuid(p.id)};`);
}
out.push("");

writeFileSync(outPath, out.join("\n"), "utf8");
const skuCount = products.reduce((acc, p) => acc + p.skus.length, 0);
console.log(
  `✅ wrote ${outPath}\n   company=1 materials=${materials.length} assets=${gltfAssets.length} styles=${styles.length} products=${products.length} skus=${skuCount}`,
);
